import type { Game } from "@/lib/types";
import { artSvg, type ArtSubject, type ArtSvgOptions, type ArtVariant } from "./art-scene";

/* ===========================================================================
 * Key-art component
 * ---------------------------------------------------------------------------
 * All of the drawing lives in ./art-scene.ts, which is plain TypeScript with no
 * JSX. That keeps the generator importable from Node (scripts render it to PNG
 * for visual QA) and means this file only has to hand the markup to React.
 * ======================================================================== */

export type { ArtVariant } from "./art-scene";
export { motifFor } from "./art-scene";

export interface GameArtProps extends ArtSvgOptions {
  game: ArtSubject;
}

export function GameArt({ game, variant, index, hue, className, showTitle, ariaLabel }: GameArtProps) {
  return (
    <div
      className={className}
      role="img"
      aria-label={ariaLabel ?? `${game.title} key art`}
      // The markup is generated by our own deterministic renderer from the
      // record's own fields, with all text XML-escaped in artSvg().
      dangerouslySetInnerHTML={{
        __html: artSvg(game as ArtSubject, { variant, index, hue, showTitle, ariaLabel }),
      }}
    />
  );
}

/** Convenience for callers that only have a full Game record. */
export function gameArtSubject(game: Pick<Game, "slug" | "title" | "genre" | "accentHue" | "rating">): ArtSubject {
  return game;
}
